version: '3.7'

services:
  tgbot:
    build: .
    command: python3 tgbot.py
    environment:
      - TGBOT_TOKEN=<API_KEY>
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pgpassword
    ports:
      - 5432:5432
